# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "2"

services:
  ordererAlice.example.com:
    extends:
      file: base/orderer.base.yaml
      service: orderer.base
    container_name: ordererAlice.example.com
    volumes:
      # mapping data from docker to local storage
      - ./chainData/orderer/ordererAlice/:/var/hyperledger/production/
      - ./crypto-config/ordererOrganizations/example.com/orderers/ordererAlice.example.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/example.com/orderers/ordererAlice.example.com/tls:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050
    extra_hosts:
      - "ordererAlice.example.com:10.171.5.32"
      - "ordererBob.example.com:10.171.5.128"

      - "peer0.Alice.example.com:10.171.5.32"
      - "peer0.Bob.example.com:10.171.5.128"

      - "zooKeeperAlice:10.171.5.32"
      - "kafkaAlice:10.171.5.32"

      - "zooKeeperBob:10.171.5.128"
      - "kafkaBob:10.171.5.128"
