# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "2"

services:
  zookeeperBob:
    container_name: zookeeperBob
    extends:
      file: base/zookeeper.base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zooKeeperAlice:2888:3888 server.2=zooKeeperBob:2888:3888
    volumes:
      # 数据固化，将zookeeper产生的数据映射到本地，当zookeeper丢失等风险是不至于数据丢失
      - ./chainData/zookeeper/data/zookeeperBob/:/data/
    extra_hosts:
      - "zooKeeperAlice:10.171.5.128"
      - "kafkaAlice:10.171.5.128"
      - "zooKeeperBob:10.171.5.32"
      - "kafkaBob:10.171.5.32"
